
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  about: [
    {
      type: 'doc',
      id: 'README',
    },
    {
      type: 'autogenerated',
      dirName: 'documentation',
    },
    {
      type: 'doc',
      id: 'compliance',
    },
    {
      type: 'category',
      label: 'Developing',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Leadership',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'leadership',
        },
      ],
    },
    {
      type: 'category',
      label: 'Web Development',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'web',
        },
      ],
    },
  ],
  practices: [
    {
      type: 'doc',
      id: 'practices',
    },
    {
      type: 'category',
      label: 'AppEng',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'appeng',
        },
      ],
    },
    {
      type: 'category',
      label: 'InfraSec',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'infrasec',
        }
      ],
    }
  ],
  'incident-response': [
    {
      type: 'category',
      label: 'Incident Response',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'incident-response',
        }
      ],
    }
  ]
};
